### ISSUE TITLE
Alarm Entity first entry last time is wrong.

### ISSUE THREAD

**Issue by flyingsubs** [royto/logbook-card#10]
![image](https://user-images.githubusercontent.com/53784637/71565634-927af900-2a7e-11ea-99d1-2163ef6aef8b.png)

The first entry as you can see is 9 minutes. Not sure where the 9 minutes is coming from but it should be 0m or hidden.

Awesome work! Thank you!

**Comment by royto** [comment]
Hi @flyingsubs , 

I just fix an issue with duration calculation in 0.4.2. Could you check it ?

**Comment by flyingsubs** [comment]
Sounds good, just updated, so far so good! Thank for updating!
