### ISSUE TITLE
Custom icon based on attibute value

### ISSUE THREAD

**Issue by PavelD** [royto/logbook-card#102]
Hello,

I have sensor updated with new video / movie title played on my projector. The attribute I used for the application (YouTube, YouTube Kids, Kodi, ...). The card is great but I'm not able to change icon based on the attribute value.

It will be great to be able to set icon (+ icon color) based on the attribute value.

**Comment by kosmaluk** [comment]
I also use this card and I am delighted with it. I can finally view the attribute history of my selected entities. What I'm missing is mapping the icon and icon color to the attribute state, so I'm also asking for such a function.

**Comment by royto** [comment]
Hello, 

Home assistant [saves history on state change but not on attributes changes](https://community.home-assistant.io/t/how-to-access-the-attribute-of-an-entity/205222/8).

So if only the attribute change, there is no history on the changes recorded. So, to me, the value of the attribute could be wrong ...

What is your use case ?

**Comment by kosmaluk** [comment]
Hi. HA records how an entity's state and attributes change with it. I see
these attributes in history.
Your tab allows you to change the icon and icon color by changing the state
of the entity, and I have multiple entities whose state is heterogeneous
and whose attribute is constant, and I would like to change the icon based
on the value of that attribute. E.g:
entity status: Love in Paradise (song title)
attribute1 - Title: my songs
attribute2 - Artist: Happiness
attribute3 - Apps: spotify.music

I want to set a different icon for all items with an attribute value of
Apps=spotify.music

You already have something similar and it works with the option:
hidden_state:
  attribute:
    name: Applications
    value: spotify.music
I'm trying to achieve this via card-mod but I can't figure out how to do
it. the color of all entities changes
See forum post:
https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/5993

śr., 7 lut 2024, 20:51 użytkownik Julien Roy ***@***.***>
napisał:

**Comment by royto** [comment]
ok. i see. what is the integration you are using ?

**Comment by kosmaluk** [comment]
I have HAOS, Core 2024.1.5, OS 11.4, Supervisor 2024.01.1 card-mod 3.4
everything latest
Your custom:logbook-card latest 2.3.0

śr., 7 lut 2024, 21:37 użytkownik Julien Roy ***@***.***>
napisał:

**Comment by royto** [comment]
I was talking about [integration](https://www.home-assistant.io/integrations/)

**Comment by kosmaluk** [comment]
Hi.
I don't understand what integration you mean?
I have a lot of integration.

In your cards I have entities from various integrations, mainly mobile.app
(sensors), and template_sensor if that's what you mean, if not please
explain.

czw., 8 lut 2024, 09:13 użytkownik Julien Roy ***@***.***>
napisał:

**Comment by royto** [comment]
my point is that if the sensor is a template sensor, you can change the icon directly in the template depending on the attribute value

**Comment by kosmaluk** [comment]
yes i know. I have itbut the color of the icon can not be set in this template sensor. That's why I want to do it in the card.You do this via state_map, but you map the icon and icon color to the entity state, not the attribute.Maybe you can write what elements and how you change them, maybe it will help me use it in card-mod

**Comment by kosmaluk** [comment]
ok, thanks for the functions, it works great, but I have a problem with specifying a wildcard for a multi-level state.
Maybe you know how to do it?

my cod:
`type: custom:logbook-card
show:
  end_date: false
  start_date: true
  separator: true
  duration: true
separator_style:
  color: '#3D3D3B'
entity:
  - sensor.notify_last_redmi_all_attr
title: ''
state_map:
  - value: '*'
    icon_color: '#1E90FF'
    attributes:
      - name: Apps
        value: com.miui.misound
  - value: '?'
    icon_color: '#094689'
    attributes:
      - name: Apps
        value: pl.pkobp.iko
  - value: '*'
    icon_color: green
    attributes:
      - name: Apps
        value: com.spotify.music`

cards pl.pkobp.iko - silver bank is not working:
![IMG_20240318_161115](https://github.com/royto/logbook-card/assets/126351906/f5784b42-53d3-4d3f-ae91-5886c172190e)

**Comment by royto** [comment]
is it because your are using `- value: '?'` ?
Can you try with `- value: '*'`

**Comment by kosmaluk** [comment]
I  tried '*' and it doesn't work. these are multi-line messages from electronic banking. The items directly pl.pkobp.iko and android.messenging do not work
![IMG_20240318_174837](https://github.com/royto/logbook-card/assets/126351906/9e623d37-d910-459c-9328-3840b1d5e245)

**Comment by royto** [comment]
can you try with 

```
  - icon_color: '#094689'
    attributes:
      - name: Apps
        value: pl.pkobp.iko
```

**Comment by kosmaluk** [comment]
this doesn't work either

**Comment by royto** [comment]
Can you give me the response of the call of the history for your entity. Go to the developer console (F12), in the network tab, the response of the call to the history API. The URL should looks something like this https://YOUR_HA_URL/api/history/period/2023-10-25T20:29:25.120Z?filter_entity_id=sensor.notify_last_redmi_all_attr

Only one response is needed

**Comment by kosmaluk** [comment]
sorry but I don't know how to response it (APi history). I go to the console and the network tab and I don't know what to do

**Comment by royto** [comment]
Open the dev tools (F12)
1. Go to network
2. find the request 
3. Go to Response tab
4. Copy the response and paste it here 

![image](https://github.com/royto/logbook-card/assets/6990995/309de649-b4ed-4178-8b44-ca719a0dd5ed)

**Comment by kosmaluk** [comment]
![IMG20240318212918](https://github.com/royto/logbook-card/assets/126351906/c1e4beb8-6330-4c2a-a72a-65700144e026)

**Comment by kosmaluk** [comment]
![IMG20240318213212](https://github.com/royto/logbook-card/assets/126351906/091a9d2e-0c9a-4727-9aa6-68524d384acb)

**Comment by royto** [comment]
it is linked with the use of `\n` in the state causing the matching to fail. Is it something that you can change ?

**Comment by kosmaluk** [comment]
I have two sensors, one original is "last notification" from mobile_app integration (Android os) and the other is a template sensor whose state is the state of the first one.
The system formats this sensor state itself, although I could try to convert the template sensor state into one line (without \n).
With this knowledge, I can also try to search for wilcard for the expression with \n from Gpt chat.
Alternatively, consider whether you can make this function so that the entity state is not required (only the attribute state is required).

**Comment by kosmaluk** [comment]
Ok, I've finished the tests and here it is:

1. There is no wildcard for multi-level entity states. Other expressions and filters for this state also do not work.
2. I converted the original sensor state to sensor template remove \n and your function worked.

Since I mainly use logbook with this template sensor, this solution finally suits me.

Thanks for the help.

I also remind myself in my other new topic regarding the new version 2.5.1 where my cards are empty :)

this is card after removed \n

![IMG_20240320_132449](https://github.com/royto/logbook-card/assets/126351906/43728466-cdb6-428c-ac40-d9a965759c5c)

**Comment by PavelD** [comment]
Thanks a lot! It works ex expected!

**Comment by ildar170975** [comment]
> So if only the attribute change, there is no history on the changes recorded

This is not correct.
On every attribute change a new row is added into `states` table.
The `states` table may contain rows with SAME state & different data in `attributes_id` column; the `attributes_id` points to a record in `states_attributes` table.
