### ISSUE TITLE
actions not working

### ISSUE THREAD

**Issue by Hogri** [royto/logbook-card#109]
**Describe the bug**
In the readme under options tap_action, hold_action and double_tap_action are listed , but don't seem to work.

**To Reproduce**
I tried it with a simple switch, but tapping the card doesn't do anything (see configuration below).

**Expected behavior**
The switch being toggled when the card is tapped.

**Environment:**
 - HA Version: 2024.2.5
 - Browser: Firefox and Android app
 - Card version: 2.4.0

**Card configuration**
```
type: custom:logbook-card
entity: switch.pflanzenlampe_aloe_sockel_1
tap_action:
  action: toggle
```

**Additional context**
I'm a HA-beginner, the problem might be me.

**Comment by igorski88** [comment]
Same here. Actions don't work.
