### ISSUE TITLE
Add option to show last time something was executed

### ISSUE THREAD

**Issue by flyingsubs** [royto/logbook-card#11]
Was thinking it would be cool to show the time since it last ran. Like if something ran at 3pm and its 3:01pm it would show 1 minute. if an hour elapsed show 60 or 1h.  This is my first feature request, I'm not sure if im able to apply the label, but thank you again for the hard work!

**Comment by flyingsubs** [comment]
I think this already exists and I didn't see how to do that. Looking into it now

**Comment by Palleri** [comment]
How and where is the information about this?

**Comment by flyingsubs** [comment]
> How and where is the information about this?

Sorry not sure as I never found it and I am no longer using this.
