### ISSUE TITLE
The attribute of the entity is not displayed in the card if its value is zero

### ISSUE THREAD

**Issue by il77781** [royto/logbook-card#112]
Hello!
Actually, I have already fully described the problem in the title: the attribute of the entity is not displayed in the card if its value is zero... I don't even know what else to add... The attribute exists (that is, it is not "none") and when its value is not 0, it is displayed completely normally... As soon as its value becomes 0, it disappears from the card...
What could be the problem here?
I don't know if it's important, this attribute gets its value from the mqtt message...

**Comment by il77781** [comment]
@royto, thank you very much for such a quick reaction! But, unfortunately, nothing has changed after the upgrade to version 2.5.1... I even re-created the card, but so far everything is unchanged...

**Comment by royto** [comment]
Can you give me the response of the call of the history for your entity. Go to the developer console (F12), in the network tab, the response of the call to the history API. The URL should looks something like this https://YOUR_HA_URL/api/history/period/2023-10-25T20:29:25.120Z?filter_entity_id=automation_covers_log_entity&end_time=2023-10-27T20:29:25.120Z

**Comment by il77781** [comment]
@royto, I probably don't quite understand what I need to do...) I use the HA app on Android, can I somehow do what you're talking about with it?

**Comment by royto** [comment]
You should do it with a browser

**Comment by il77781** [comment]
@royto, anyway, I logged in through the browser... Pressed F12, found the "network" tab.... I even found a certain input field in which, in theory, I can specify a filter... In this field, I entered the text that you wrote (with a replacement for my HA_URL and setting the end time to 2024-03-18... But, unfortunately, I do not understand further where to get "response of the call of the history for my entity". At least, I don't see anything like it here... Here, if it is not difficult for you, some further explanations are needed... Or a link to a source where I can read about it... 
But that's not the most important thing! 
When I logged into my HA through the browser, an attribute with a zero value was displayed on the card! And now I don't even know if it was displayed there before (when using the browser). But through the HA app for Android (on two devices), this attribute is still not displayed!!!). I don't know if it helps at all, but I cleared the browser cache on my Android device, exited the app and logged in again... And still the attribute is not displayed! But if I log to HA on this Android device through a browser, it is displayed! I don't know what to think anymore...

**Comment by il77781** [comment]
I think I figured it out a little bit... For some reason, I don't have https, but just http here... Entries appear approximately every 5 seconds... Do you need any of these records? If yes, then if you go to the "Response" tab, we will get a very large portion of information... I'm not sure if it's worth putting it in here... But it contains an attribute of interest to me, which is equal to zero... Should I still insert this response here?

**Comment by royto** [comment]
Yes, only one response is needed. the card refresh data every 5s. The easiest way is to copy all the response (you can use the `hours_to_show` to limit the amount of data if you want ...)

**Comment by il77781** [comment]
@royto, If I was finally able to understand you correctly, then I limited the amount of data in the card settings (set 1 hour). This is the response I got:
[[{"entity_id":"sensor.air_co2","state":"613","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:05:42.989000+00:00","last_updated":"2024-03-18T07:05:42.989000+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"616","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:07:20.923172+00:00","last_updated":"2024-03-18T07:07:20.923172+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"617","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:09:20.915846+00:00","last_updated":"2024-03-18T07:09:20.915846+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"616","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:11:20.915049+00:00","last_updated":"2024-03-18T07:11:20.915049+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"613","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:15:20.941689+00:00","last_updated":"2024-03-18T07:15:20.941689+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"608","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:17:20.915155+00:00","last_updated":"2024-03-18T07:17:20.915155+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"609","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:19:20.921313+00:00","last_updated":"2024-03-18T07:19:20.921313+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"610","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:21:20.947222+00:00","last_updated":"2024-03-18T07:21:20.947222+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"612","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:23:20.915245+00:00","last_updated":"2024-03-18T07:23:20.915245+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"609","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:25:20.919361+00:00","last_updated":"2024-03-18T07:25:20.919361+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"606","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:27:20.941320+00:00","last_updated":"2024-03-18T07:27:20.941320+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"604","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:31:20.933695+00:00","last_updated":"2024-03-18T07:31:20.933695+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"603","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:33:20.910860+00:00","last_updated":"2024-03-18T07:33:20.910860+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"602","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:35:20.911530+00:00","last_updated":"2024-03-18T07:35:20.911530+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"604","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:37:20.918329+00:00","last_updated":"2024-03-18T07:37:20.918329+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"601","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:39:20.914526+00:00","last_updated":"2024-03-18T07:39:20.914526+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"600","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:43:20.917832+00:00","last_updated":"2024-03-18T07:43:20.917832+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"602","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:47:20.938906+00:00","last_updated":"2024-03-18T07:47:20.938906+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"615","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:49:20.911040+00:00","last_updated":"2024-03-18T07:49:20.911040+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"618","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:51:20.908315+00:00","last_updated":"2024-03-18T07:51:20.908315+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"627","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:53:20.945755+00:00","last_updated":"2024-03-18T07:53:20.945755+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"632","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:55:20.914681+00:00","last_updated":"2024-03-18T07:55:20.914681+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"630","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T07:59:20.947562+00:00","last_updated":"2024-03-18T07:59:20.947562+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"632","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T08:01:20.910198+00:00","last_updated":"2024-03-18T08:01:20.910198+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}},{"entity_id":"sensor.air_co2","state":"639","attributes":{"idn":0,"unit_of_measurement":"ppm","device_class":"carbon_dioxide","friendly_name":"Qingping Air Monitor Датчик CO2"},"last_changed":"2024-03-18T08:03:20.905379+00:00","last_updated":"2024-03-18T08:03:20.905379+00:00","context":{"id":"01HS71E2HXAS6M6CPM8B9KHD3D","parent_id":null,"user_id":null}}]]
I am interested in the "idn" attribute... As you can see, in this response it is zero... But, again, I now see this attribute through the browser (but I'm not sure that it wasn't visible before, since I used the application), but I still don't see it in the application...

**Comment by il77781** [comment]
@royto, hello!
Tell me, please, is it possible to solve the problem I described somehow?
At the moment, nothing has changed: in the application (specifically in the application) it still does not show attributes equal to zero... (

**Comment by royto** [comment]
It stills does not work on your android app ?

It works on mine ... 

![image](https://github.com/royto/logbook-card/assets/6990995/b18989dc-f745-427d-9240-fd8ed84f2c38)


There is no specific code for android vs browser ...

**Comment by il77781** [comment]
@royto, in version 2.5.3, everything worked correctly for Android apps! It was enough to clear the application cache! In this case, it was not necessary to clear the browser cache. 
Maybe everything worked on version 2.5.1, but then I did not clear the application cache, but only the browser cache... Perhaps this was my mistake...
Thank you very much!
