### ISSUE TITLE
Logbook card is rarely able to calculate duration

### ISSUE THREAD

**Issue by Dinth** [royto/logbook-card#12]
Logbook shows start and end time for each event correctly, but rarely is able to calculate duration based on that.
![Screenshot from 2019-12-31 08-32-49](https://user-images.githubusercontent.com/313674/71615357-cbaf8800-2ba8-11ea-8333-9e6ef828c8e0.png)

**Comment by royto** [comment]
Do you still have the issue ?
What is the configuration of the card ?

**Comment by Dinth** [comment]
no to be honest i have just noticed (im not checking vacuum cleaning log often) that the issue is gone. I dont know why though, i havent changed anything.

**Comment by royto** [comment]
Good to hear. I'll close the issue. Re open it if the issue is still there
