### ISSUE TITLE
Support more than one entity

### ISSUE THREAD

**Issue by flouck** [royto/logbook-card#13]
Reproduce a view similar to the Home Assistant logbook, including a list of entities and visualize events on a timeline.

**Comment by jaburges** [comment]
same here. Not sure if this is your goal but came here looking for a logbook card. This looks great, but is more of a history of one item card. 
It would be amazing to have a feed just like the logbook

**Comment by triblondon** [comment]
I've been trying to achieve a visitor logbook for my house, something like this:

```
# Visitors

## Yesterday
Andrew                          14:15 - 17:23 (3hrs 7 mins)
Andrew                          08:00 - 08:14 (14 mins)
Jane                            Present all day

## Wednesday
Andrew                          14:15 - 17:23 (3hrs 7 mins)
```

Using your card @royto I've gotten close - I can have one card per possible visitor.  Being able to have more than one entity per card would enable this use case - though you'd also need to be able to customise the main text for each entry on the card (currently always the state, but in the above use case it's the entity name).

I'd be happy to give this a go if you would support the idea and in principle open to merging that kind of change.

The use case example above also groups the entries into time periods of one day but I'll open a separate issue for that.

**Comment by royto** [comment]
I'm open to pull request

I haven't lot of time right now to work on the card.

**Comment by SteffenM-DE** [comment]
It would be helpfull to add entities with wildcards and domains too.

So we can for example show a automation history of all automations without add all single automations. Exceptions could be defined with hidden_state and so we can mix it like we want.

**Comment by kalhimeo** [comment]
very nice card, but this feature would make it fantastic :-) thanks for the great work

**Comment by criticallimit** [comment]
Is there any progress regarding multi-entity function?

**Comment by mesut3000** [comment]
It would be awesome to have multiple entities on your card.

**Comment by maxclevenson** [comment]
Rape On Nov 2, 2023, at 1:00 AM, mesut3000 ***@***.***> wrote: It would be awesome to have multiple entities on your card. — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

**Comment by nicop4** [comment]
Nice job @royto 👍

**Comment by kalhimeo** [comment]
very nice indeed ! Any chance to have a "label" option for the entities in order to rename the way they are shown ? Thanks !

**Comment by royto** [comment]
@kalhimeo it is possible yes 😉. Could you open a new issue as feature request please

**Comment by kalhimeo** [comment]
alright I will do that now, thanks again for the super active support !

**Comment by mstuij** [comment]
Thanks for adding it!

**Comment by maxclevenson** [comment]
RapeSent from my iPhoneOn Nov 2, 2023, at 3:53 PM, Max Clevenson ***@***.***> wrote:﻿RapeOn Nov 2, 2023, at 1:00 AM, mesut3000 ***@***.***> wrote:It would be awesome to have multiple entities on your card.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
