### ISSUE TITLE
Time is wrongly shown when "date_format" defined

### ISSUE THREAD

**Issue by ildar170975** [royto/logbook-card#132]
**Describe the bug**
Consider the code:
```
type: custom:logbook-card
entity: sun.sun
title: ''
hours_to_show: 48
date_format: dd/MM/YYYY hh:mm
```
![image](https://github.com/user-attachments/assets/21e5d756-c972-4095-9bed-000380ea33fc)

And compare with a default date format:
![image](https://github.com/user-attachments/assets/e4a3d66f-5a92-4a8c-a98c-8e7f54f36f82)

Note that:
- day is incorrect 
- hours are always < 12

**Expected behavior**
Time is properly shown for a specified format.

**Environment (please complete the following information):**
 - HA Version: 2024.7.3
 - Browser: Chrome 127.0.6533.89 
 - Card version: 2.5.5

**Card configuration**
Add your configuration here

**Additional context**

**Comment by ildar170975** [comment]
Note that same issue is visible in Readme:

![image](https://github.com/user-attachments/assets/1815b363-3baf-4678-a8ac-2e13b6129787)

**Comment by ildar170975** [comment]
I am closing the issue - but suggest @royto to edit Readme.

**Comment by royto** [comment]
Thanks for the report. README has been updated
