### ISSUE TITLE
Display how long the event has been triggered

### ISSUE THREAD

**Issue by royto** [royto/logbook-card#16]
From issue #15 raised by @iptvcld.

For example, if the event has been triggered yesterday, we should display `1 day ago`

Should be displayed by default ?
Should be an alternative of date (start / end date) ?
Where to display it ?

**Comment by iptvcld** [comment]
how do we configure this?
I tried doing this
        title: 'Incoming Call Log'
        type: 'custom:logbook-card'      
        show:
          end_date: false
          start_date: true
          duration: true  
          duration_labels:
            minutes:

**Comment by iptvcld** [comment]
Looks good thanks! Can we also add lets say a line break after each entry?  Something think and light

**Comment by iptvcld** [comment]
also just noticed if we do this
        duration_labels:
          seconds: '${value} seconds ago'
          minutes: '${value} minutes ago'
          hours:   '${value} hours ago'
          days:    '${value} day ago'
        type: 'custom:logbook-card'  

After day 1 - lets say day 2.  This will say '2 day ago'.  The grammar wont make sense and should say '2 days ago'  and i cant it to days ago - then day 1 wont make sense. It will say '1 days ago'

**Comment by royto** [comment]
> 
> 
> Looks good thanks! Can we also add lets say a line break after each entry? Something think and light

You should open an issue about this

**Comment by royto** [comment]
@iptvcld I just open the issue. I just release a version with support of localization of duration.

It still needs to be developed
