### ISSUE TITLE
Add possibility to set custom label when duration value is 1

### ISSUE THREAD

**Issue by royto** [royto/logbook-card#17]
also just noticed if we do this
        duration_labels:
          seconds: '${value} seconds ago'
          minutes: '${value} minutes ago'
          hours:   '${value} hours ago'
          days:    '${value} day ago'
        type: 'custom:logbook-card'  

After day 1 - lets say day 2.  This will say '2 day ago'.  The grammar wont make sense and should say '2 days ago'  and i cant it to days ago - then day 1 wont make sense. It will say '1 days ago'

_Originally posted by @iptvcld in https://github.com/royto/logbook-card/issues/16#issuecomment-606064315_

**Comment by iptvcld** [comment]
I added this
        duration_labels:
          second:  '${value} second ago'
          seconds: '${value} seconds ago'
          minute:  '${value} minute ago'
          minutes: '${value} minutes ago'
          hour:    '${value} hour ago'
          hours:   '${value} hours ago'
          day:     '${value} day ago'
          days:    '${value} days ago'
        type: 'custom:logbook-card' 

But it still shows 1 minutes ago - am i doing this wrong?

**Comment by royto** [comment]
What version are you using ? Verify you have the version 0.5.2 installed

**Comment by iptvcld** [comment]
Logbook Card
Logbook card for Home Assistant UI Lovelace
GitHub stars: 19
Last updated: 23 hours ago
Installed: 0.5.2

**Comment by royto** [comment]
Normally it should works. Can you try refresh your page to be sure the card is up to date ?
