### ISSUE TITLE
Feature request: map entity value to a custom text

### ISSUE THREAD

**Issue by nicop4** [royto/logbook-card#2]
Hi,

Very useful card :)

I suggest an improvement: let the user map the displayed entity value to a custom one.
Example: I track my heating usage, and the value is `heat`, it would be nice to have `heating on` or whatever value that could be the translation to your own language.

Look forward to that! 👍

**Comment by royto** [comment]
Nice Idea ! Thanks for your feature request

**Comment by royto** [comment]
Will be available in v0.2.0
