### ISSUE TITLE
Custom element doesn't exist: logbook-card after update

### ISSUE THREAD

**Issue by iptvcld** [royto/logbook-card#24]
- url: /local/community/logbook-card/logbook-card.js
      type: module

**Comment by iptvcld** [comment]
Just noticed that the file name in the logbook-card folder is (rollup.config.js)

**Comment by royto** [comment]
I forgot to upload the file in the release. It should be good. Can you try reinstall the version ?

**Comment by iptvcld** [comment]
looks good!
