### ISSUE TITLE
hiddenState

### ISSUE THREAD

**Issue by stavroz** [royto/logbook-card#30]
The hiddenState option does not seem to work. I am running 0.112.4

**Comment by royto** [comment]
What is the configuration of your card ? 

You need to set the  state with it's English value not with the translated one

**Comment by stavroz** [comment]
- type: "custom:logbook-card"
        desc: true
        max_items: 5
        entity: switch.plug_158d0001db064f
        title: Heater History
        hiddenState:
          - Off
        show:
          end_date: false
          start_date: true
          separator: true

[image: image.png]

does this look correct?

**Comment by royto** [comment]
The issue is the case. You should use `off` and not `Off`

See in the developement tools values of some of my switch

![image](https://user-images.githubusercontent.com/6990995/87909895-5edadd00-ca69-11ea-802c-756394dfd9e5.png)

**Comment by stavroz** [comment]
I tried that. Still shows off

[image: image.png]


   I also tried with other entities with words like idle etc.

**Comment by royto** [comment]
I can't see your image.

Working good for me.

Can you see if you have errors in the browser console ?

**Comment by stavroz** [comment]
No errors in the web console. I also can't get the state_map to work.
Everything else seems ok.

FYI I am running the docker version of HA.

**Comment by royto** [comment]
What is your browser ? And it's version ? 

Have you try another browse ?

**Comment by stavroz** [comment]
I tried firefox and chrome both are up to date.

I saw an error with another unrelated community plugin but not this one.

I also tried manipulating the line

hiddenState:

multiple ways ( eg lower case s, wrong spacing ) and it definitely throws
up an error if i put in the wrong format.

it is in the correct format however there are no errors but it does not
work as expected.

I've tried re-installing the plugin.

I dont know what else to try.

**Comment by royto** [comment]
Can you check in the network tab of your browser. You should see call like this

![image](https://user-images.githubusercontent.com/6990995/88028738-5651d780-cb39-11ea-8553-90da2dc67f19.png)

Find one with your entity. In the response tab, should see the history. There is a state prop for each value

![image](https://user-images.githubusercontent.com/6990995/88026852-bb57fe00-cb36-11ea-878a-68a6ddcc5292.png)

You should use the same value

**Comment by stavroz** [comment]
In this case I am trying to remove idle and unavailable entries from the
logs.

[image: image.png]

      - type: "custom:logbook-card"
        desc: true
        max_items: 10
        entity: sensor.tomatoes_station_status
        title: Tomatoes History
        hiddenState:
          - unavailable
          - idle
        show:
          end_date: false
          start_date: true
          separator: true

**Comment by royto** [comment]
Once again I can't see your images so it's hard to help ...

**Comment by royto** [comment]
Maybe you can use image sharing website like [imgur](https://imgur.com/upload)

**Comment by stavroz** [comment]
How is this?..

In this case I am trying to remove idle and unavailable entries from the
logs.

https://i.imgur.com/eoFX8Aw.png

      - type: "custom:logbook-card"
        desc: true
        max_items: 10
        entity: sensor.tomatoes_station_status
        title: Tomatoes History
        hiddenState:
          - unavailable
          - idle
        show:
          end_date: false
          start_date: true
          separator: true

**Comment by royto** [comment]
I just tested with one of my entitites wich has idle state and its is working with your configuration ...

**Comment by bal1983** [comment]
Had the same problem. Changing off to 'off' has solved for me.

**Comment by SdeGeata** [comment]
Doesn't work for me either. I am using it with an input select, my default is "Select...". This is configured in the config. No go, still visible.

![Screen Shot 2021-03-18 at 1 53 36 PM](https://user-images.githubusercontent.com/5808871/111673479-679ad300-87f1-11eb-8983-9b0dd985e0d3.png)

As you can see, you can still see those entries.. as well as the "off" I tested.

**Comment by royto** [comment]
Seems that you have a indentation issue

hiddenState is not under show. Remove the 2 spaces to align with others properties. Like this: 

```yaml

collaspe: 3
show:
  state: true
  duration: false
  ...
hiddenState: 
  - Select...
  
```

**Comment by SdeGeata** [comment]
That was indeed the issue. Problem solved. Thanks!
