### ISSUE TITLE
Can't install card

### ISSUE THREAD

**Issue by xvolte** [royto/logbook-card#31]
I have HACS, but i'm unable to find the "logbook" module / theme or card.
it says, "no repository".

So i thought, no problem, i'll install manually and link the resources : Yes, but the README says we are supposed to have a file named logbook-card.js, which is no where to be found on the github repo.

Could you help ?

![norepologcard](https://user-images.githubusercontent.com/21142611/89462879-650dd080-d76e-11ea-9844-e463b94d26f0.png)

**Comment by royto** [comment]
the name is `Logbook Card` with dash

![image](https://user-images.githubusercontent.com/6990995/89464192-51636980-d770-11ea-93d4-c64b1716bb68.png)

You should be able to find it in HACS.

For manual installation, te js file is transpiled from TS to JS and available in [releases](https://github.com/royto/logbook-card/releases) => The [v1.2.0](https://github.com/royto/logbook-card/releases/tag/1.2.0)  

![image](https://user-images.githubusercontent.com/6990995/89464465-d2226580-d770-11ea-885f-3937976c31a1.png)

**Comment by flixlix** [comment]
You are searching for repositories that you already have  installed, you need to first click the bottom-right button that says `Explore & Add Repositories` and then search for the card.
