### ISSUE TITLE
cannot locate logbook card?  need a hint please

### ISSUE THREAD

**Issue by fireheadman** [royto/logbook-card#34]
I installed the logbook-card from HACS, however I do not see where/how it is implemented.

Can someone please offer some hints/documentation as to where it is located and how to use it?
![image](https://user-images.githubusercontent.com/19847195/96168119-8f51dc00-0edd-11eb-8f5f-4c0d485f5d0f.png)

Nothing comes up for this card...
![image](https://user-images.githubusercontent.com/19847195/96168224-b3adb880-0edd-11eb-95f0-975e29b9fbf9.png)

**Comment by royto** [comment]
You need to create a manual card and configure the card using yaml configuration following the documentation of the readme.md

**Comment by fireheadman** [comment]
thanks... will give that a shot.

**Comment by fireheadman** [comment]
works perfect... thank again for the tip.
Just had to look up correct entities to get it to display using manual card.
