### ISSUE TITLE
FR: Allow define last X events to display rather than time period

### ISSUE THREAD

**Issue by scstraus** [royto/logbook-card#38]
Hi, I've been using similar functionality to this card in my [alarm dashboard](https://github.com/scstraus/home-assistant-config#tab-6-alarm) for quite a while with the home-feed custom card. Your card is much faster and I would like to switch to it, but having to defining a time period rather than number of events to show is keeping me from using it. The problem for a security application like mine is that I might have gone on vacation for 2 weeks and want to check if any motion or open doors were detected in that time frame. If I define a 2 week period and I'm home during that time, there will be thousands of motion events displayed, but if I'm gone, it will just show me the relevant last events (which hopefully were just me leaving the house before holiday).  Thousands of events don't really help.

Hope you'd consider this as I really like using the standard set of cards where possible. Great card otherwise. Impressive speed!

**Comment by royto** [comment]
there is already an option `max_items`

![image](https://user-images.githubusercontent.com/6990995/99802338-d748cc00-2b37-11eb-9fbd-122175a0c2e6.png)

Should fit your need ...

**Comment by scstraus** [comment]
Wow, how in the world did I miss that? Sorry.
