### ISSUE TITLE
Any way to have wildcards in state_map?

### ISSUE THREAD

**Issue by emufan** [royto/logbook-card#42]
Any way to have wildcards in state map?

I have several sensors where the search-string is only at the beginning, end or somewhere in the middle of the state. So 

- icon: 'mdi:stove'
    value: Kitch*
or *itchen
*thch*

would be needed/very helpfull.

Any way to have to already configured (and I'm only not able to find) or possible/planned?

**Comment by mkanet** [comment]
This is EXACTLY the feature I'm looking for.  I'm looking for a way to display "filtered" history of an entity.  Currently, I don't think there's any way to do this in Home Assistant.

https://www.reddit.com/r/homeassistant/comments/nfoi9m/how_to_filter_history_of_an_entity/
https://community.home-assistant.io/t/history-filter/13927

**Comment by royto** [comment]
Done in 1.4.0
