### ISSUE TITLE
Logbook card shows too much history data, when + is pressed on phone. It crashes. 

### ISSUE THREAD

**Issue by MrPsyko** [royto/logbook-card#46]
I use this card, it's good. Only got crashing home assistant when pressing in the lovelace UI. 

It tries to show a long preview history logbook card,

Maybe checkbox for show max 10 values ?

Old note 8 but repeatable on note 10+. N20ultra, s21 u

Also disabling quickly fixes the problem, no more crashing home assistant app./.
![Schermafbeelding 2022-02-10 004058](https://user-images.githubusercontent.com/49487741/153309569-3b022118-40e2-442d-8ae0-5336d8267300.png)
![Schermafbeelding 2022-02-10 004017](https://user-images.githubusercontent.com/49487741/153309574-aa26a7c0-42dd-464c-b06c-a0a4f9b53d34.png)

**Comment by royto** [comment]
Hi, 

yes by default the card will show all events in the selected period.

Use `max_items` to limit the number of items to display (you can shorten the period also).

**Comment by royto** [comment]
Maybe 3 is a little too small. 10 can be a god compromise.

**Comment by royto** [comment]
The HA logbook card is displaying also lot of events but have a scrollbar to avoid a big card

![image](https://user-images.githubusercontent.com/6990995/207724663-24dbf1b0-9208-4706-8954-08150a1d54b1.png)

could be an option to limit the height of the card.

**Comment by emufan** [comment]
I would like to see the old behavior. Or as suggested in another thread an option to switch off the scrollbars (again).

I understand if some like them, but for me on desktop chrome they are very ugly and for me this does not fit to the `history` and esp. `collapse` settings. If I set them to see 5 items, then I want to see 5 items (without scrollbar). And then (as before) an heigh extended card after clicking on de-collapse button. Both without scrollbars.
