### ISSUE TITLE
Option naming convention inconsistency?

### ISSUE THREAD

**Issue by paranoidi** [royto/logbook-card#55]
Why is `hiddenState` camel case when everything else is not?

Edit: looks like the documentation is just incorrect
Edit 2: Sorry about multiple edits, but I can not get neither hiddenState or hidden_state to work

**Comment by royto** [comment]
it is legacy 😄 

Is is something that You want to be changed ?

**Comment by royto** [comment]
@paranoidi `hiddenState` is renamed in `hidden_state` in [1.6.0 ](https://github.com/royto/logbook-card/releases/tag/1.6.0)

About not be able to make it work, do you have an example of config ?
Warning, the value should be the state value return by HA like in the developer Tools (and not the displayed value)

Here an example with sun.sun.

![image](https://user-images.githubusercontent.com/6990995/204914317-9a687eff-882b-4672-80a7-39b0739e61e7.png)

Value should be `below_horizon` and not `Sous l'horizon`  in french for example

![image](https://user-images.githubusercontent.com/6990995/204915003-c33c1cf9-dc8f-417e-bc55-b7a71adb30b2.png)
