### ISSUE TITLE
Some Enhancements if you have time 

### ISSUE THREAD

**Issue by SteffenM-DE** [royto/logbook-card#57]
Hi, 

great work for showing nice history of an entity.

I have some point with enhacemends if you like:

- The titel font and padding is very big so the card taks more space then needed. I tryed with crad-mod but could not minimize the padding. So it would nice to do some style thinks out of the box.
- An other style thing is to add an icon color option to the states to change icon and color on special states.
- It would be nice to show more then multi entities at one card, so we could show history of for example many doors etc.
- I would very nice if we can use a line break \n at the state. So I use templates to get all data in the state, but sometimes it would nice to set a line break.

Thanks you, Steffen

**Comment by SteffenM-DE** [comment]
Hi,

thank you for the comments and the solutions with Card-mod.

The point with line break I try to describe a little bit more:

I using a template to build a string from differnet entitiys and attributes, so I have a longer string in the template state. If I use this entity the state is showing at the main row of your sample it is 'Sous l'horizon'. If it is very long your card using two lines but breaks the line anywhere. With the manuel line break like other crads (Mushroom) I can make the line break on a special position. 

I hope now it's clear whats my wish abaout.

Thanks.

**Comment by royto** [comment]
Can you provide me a screenshot ?
How do you achieve that with mushrooms cards for example ?

**Comment by SteffenM-DE** [comment]
In Mushroom we can have a "\n" in a state and this is a line break so we can create a line break on a special position:

![Screen_20221201-103223](https://user-images.githubusercontent.com/10560225/205017553-afc9d6ef-3253-43e5-b680-31b21208e9aa.png)

In the scrennshot you can see your card and my long state coming from a template starting with 'Eingehnd'. The first row have no line break but the second have after the arrow showing the called number. So if I creat the tempate state for the logbook entity I want to add a line break (\n) to have always a line break bevor the arrow. So all rows show the same construction.

I hope now it's clear. Thank you very much.

**Comment by royto** [comment]
Can you show how do you do to have multiline state ... 

I tried but did not succeed to have it working ...

**Comment by royto** [comment]
Can you test using this configuration ?

```yaml
card_mod:
  style: |
    .state {
        white-space: pre-line;
    }
```

If it is working i'll add as default style for the card

**Comment by SteffenM-DE** [comment]
white-space: pre-wrap; did not work complet. I can add \n but sometimes it breaks the line if there is no \n and no reason to must break the line.

So I think Mushroom translate the \n to a linebreak so the user can decide where to break the line. Here is the example:

![Screen_20221202-111723](https://user-images.githubusercontent.com/10560225/205270281-e513a8b1-3399-4de9-a8d9-6556f7489704.png)

**Comment by royto** [comment]
Can you show me what it render on the logbook card and what you expect?

**Comment by SteffenM-DE** [comment]
Like the Mushroom scrennshot, I add \n in the template state and I want to render it as fixed line break inside the state.

Logbook look like that:
![Screen_20221203-112132](https://user-images.githubusercontent.com/10560225/205436195-c9e979d7-dffe-47ca-999e-178678f1a0b0.png)

But I have add a \n befor the small arrow to have a line break at this position, that it looks this way. Because if there are numbers the line a longer and breaks on a ugly place ansd so I have a uniformly view with always a lin breka befor the target is shown:

Unbekannt
► Geschäft

**Comment by SteffenM-DE** [comment]
Thank you, is working now.
