### ISSUE TITLE
hidden_state not working if there are more words in state

### ISSUE THREAD

**Issue by SteffenM-DE** [royto/logbook-card#59]
I try to hide states with number 061 in it and so i define that:

![Screen_20221201-104850](https://user-images.githubusercontent.com/10560225/205021020-cd1ae42a-ce5f-49bf-a195-ad76de097ac0.png)

But the card show these lines and I expected both should be hide because there is a '061':

![Screen_20221201-103223](https://user-images.githubusercontent.com/10560225/205019891-63319526-1319-4f52-b437-2173052393c8.png)

Also I define '*' as hidden state and expected there must be nothing in history but no all entries are still showing?

**Comment by royto** [comment]
Can you show me the state value for this entity the developer tools ?

**Comment by SteffenM-DE** [comment]
Here you can see the state:

![Screen_20221201-141233](https://user-images.githubusercontent.com/10560225/205061802-d8030723-d57d-4d15-8670-3d084d03e721.png)

**Comment by royto** [comment]
I didn't reproduce the issue ...

as you can see the first card have the hidden state configured and the second don't have  ...

![image](https://user-images.githubusercontent.com/6990995/205148790-28664480-29ec-48ad-a5d7-a0327e3256f4.png)

![image](https://user-images.githubusercontent.com/6990995/205148862-c683ffff-bb55-4939-a37e-a77d73ade483.png)

Make sure to have installed the 1.6.0 where I rename `hiddenState` into `hidden_state`

**Comment by SteffenM-DE** [comment]
1.6.0 is installed and it did not work but did not work with old option and older version too.

Do not know why and can not really reproduce a template:

![Screen_20221202-113211](https://user-images.githubusercontent.com/10560225/205273407-5db9d5e9-5adf-4dd6-b8ae-61c9d54fc7d1.png)

![Screen_20221202-113500](https://user-images.githubusercontent.com/10560225/205273649-813c0617-7ad9-441a-bdaa-0fcbf3cb1292.png)

**Comment by royto** [comment]
Can't figured it out why it is not working ...

![image](https://user-images.githubusercontent.com/6990995/205387584-82a3fb71-a947-42e0-bf63-25a9d080fb35.png)

![image](https://user-images.githubusercontent.com/6990995/205387633-05868c53-b029-4a6b-afa8-cca9ba634ecd.png)

can you check in the console (F12 on chrome or Firefox), and look for the card version 

![image](https://user-images.githubusercontent.com/6990995/205388018-b128860e-9a01-4233-a336-f55cc6480ca9.png)

**Comment by SteffenM-DE** [comment]
![Screen_20221203-110153](https://user-images.githubusercontent.com/10560225/205435318-58605b90-29b5-46f2-aa2a-268c0f4230c1.png)

I tryed again many variations (creating new cards and entities) but it did not work. 
![Screen_20221203-110514](https://user-images.githubusercontent.com/10560225/205435631-e2a3ffe5-a89b-4a9e-8ed4-130f8e627ed8.png)

But something with whitspace is the point. Now I use the logbook with standard person entity:

![Screen_20221203-111150](https://user-images.githubusercontent.com/10560225/205435846-771371e5-73c9-4288-8b67-963d4ecd2132.png)
![Screen_20221203-111140](https://user-images.githubusercontent.com/10560225/205435856-dad87b2e-be62-4202-b2d7-bbd31c325c92.png)
![Screen_20221203-111129](https://user-images.githubusercontent.com/10560225/205435859-3b6e9b7d-46ee-4f64-9e7a-dbdbc818200d.png)

**Comment by SteffenM-DE** [comment]
Same at state_map. I can not change the icon or color because the value with wildcard do not work:

![Screen_20221226-113512](https://user-images.githubusercontent.com/10560225/209539246-1e7c1aec-fb26-403c-b6b0-fa535e543d40.png)

If I can do something to find the bug let me know.

**Comment by royto** [comment]
Can you provide me the response payload of a call to the history rest api using the dev tools > network

the URI should be something like `https://youinstance/api/history/period/2022-12-21T20:13:20.767Z?filter_entity_id=input_text.it_fritz_lastcaller&end_time=2022-12-26T20:13:20.767Z`

If you are concerned about the data, maybe you can send it privately through twitter account or my github email ...

**Comment by SteffenM-DE** [comment]
Hi, I could not send to you via Twitter so here we are, I have only changed some numbers and characters:

`curl -X GET -H "Authorization: Bearer eyJ..." -H "Content-Type: application/json" http://myha:8123/api/history/period/2022-12-21T20:13:20.767Z?filter_entity_id=input_text.it_fritz_lastcaller
[[{"entity_id":"input_text.it_fritz_lastcaller","state":"Sa. 15:02: Surname, Steffen (0123456789)\n► Geschäft","attributes":{"icon":"mdi:phone-incoming","friendly_name":"Letzter Anrufer"},"last_changed":"2022-12-21T20:13:20.767000+00:00","last_updated":"2022-12-21T20:13:20.767000+00:00"}]]`

**Comment by royto** [comment]
I think I found the issue.

Can you test the pre-release [1.9.1-beta1](https://github.com/royto/logbook-card/releases/tag/1.9.1-beta1)

**Comment by SteffenM-DE** [comment]
Great, is working now. All filters I try on hidden_state are working fine.
