### ISSUE TITLE
Date wrong in start_date and end_date fields

### ISSUE THREAD

**Issue by cdk222** [royto/logbook-card#60]
Hi - firstly thanks for this card and your work.

Any ideas on how to fix wrong start & end date shown on the card. 

So today is Mon 5th December and the logbook-card is telling me the entity has been on.....but the reality is that it has not run today with the last correct running date being yesterday on Sun 4th December. 

You can see there also also some other issues:
- the actual Day-of-week is incorrect and not inline with the date
- there is an entry for 6th December which is into the future
- there is the first entry for **00**/12/2022

I have checked the HomeAssistant logbook and the entity entries have the correct date there so not sure what is going wrong here.

![image](https://user-images.githubusercontent.com/45811133/205669941-a884f426-aec5-4ca1-9436-2fad29359d94.png)

![image](https://user-images.githubusercontent.com/45811133/205670100-84c535e7-9243-468d-8bb5-84596a88523c.png)

**Comment by cdk222** [comment]
Ignore me - 10 minutes later I played around further with the date format......it didnt like:

dd/MM/YYYY

**** that said do you know how i can only display history items where the duration is greater than 1 min and ignore the rest?

**Comment by royto** [comment]
I can close the issue ?

**Comment by royto** [comment]
No Pb.

Thanks
