### ISSUE TITLE
With new tap action, clicking on collapse arrow not possible anymore

### ISSUE THREAD

**Issue by emufan** [royto/logbook-card#61]
With new tap action in new version 1.7.x, clicking on collapse arrow not possible anymore to extend the collapsed list.

Any chance to have this fix (locally, without disabling the great tap action) or via a fix?

**Comment by royto** [comment]
Didn't notice it.
Will try to fix it

**Comment by aheath70** [comment]
I have the same issue here. Clicking on expand arrow to extend the list pops up the more-info dialog.

**Comment by emufan** [comment]
@royto (only @ because of the closed status) Whatever happened now, now there is a scrollbar. Related to the fix?

![image](https://user-images.githubusercontent.com/22775515/209081493-15b5cd81-e579-487a-8f59-673d1f7b4fad.png)

So the card heigh is not adjusting (enough) enymore.

**Comment by royto** [comment]
This is linked to #46.

I can add an option to not have a scrollbar if needed.
