### ISSUE TITLE
Can't hide title with tittle:false after 1.8.0 update.

### ISSUE THREAD

**Issue by OneToo** [royto/logbook-card#62]
I use the following code in my custom Lovelace Dashboard layout.

```
 - type: custom:logbook-card
   max_items: 1
   title: false
```

This would normally hide the title.  Now it's just showing the word false, or any other word that's typed after title: .  
The issue persist with update 1.9.0.  Did something change in the way titles are hidden?  I'm sticking with 1.7.1 for now.  

Update:
The following worked for me.

```
card_mod:
  style: |
    ha-card .card-header {
      display: none;
    }
```
Looks like using tittle:'' works also. 

With both options, margins are misaligned between the win10 chrome browser and android app for ha-card .duration when using either % or px.

**Comment by OneToo** [comment]
The following worked for me.
```
card_mod:
  style: |
    ha-card .card-header {
      display: none;
    }
```
Is this the only way to hide the tittle now?

**Comment by royto** [comment]
I didn't know that setting false was hidding the title.
Can you try with 

````
type: custom:logbook-card
title: ''
````

**Comment by OneToo** [comment]
> I didn't know that setting false was hidding the title. Can you try with
> 
> ```
> type: custom:logbook-card
> title: ''
> ```

Sorry, i didn't put it in a code format, but i noted that i tried that already an it worked but I'm having misalignment issues now.  That may actually be due to the other entities not being formatted properly.  I think the tittle was removed but the format remained which kept alignment in sync with other entities without additional formatting requirements.  I'm currently looking at the code for the other entities.  

The duration and entity switches align right in the desktop browser, but looks centered in the android app since the latest update.  

[](https://imgur.com/34QO7rf)
