### ISSUE TITLE
Option to remove message header from state

### ISSUE THREAD

**Issue by zelo66** [royto/logbook-card#66]
Hey,

As I can't add more than one entity (normally I would create a separate sensor for information and a separate one for errors) I have to use state_map.  This is a great option, but I would like to remove the message header somehow. In my case it is "ERR" and "INF"
Is there any way to do this?

![logbook](https://user-images.githubusercontent.com/8418119/233797567-52cf65d0-c807-4091-b4dc-dac9bbe523eb.PNG)

`type: custom:logbook-card
title: Alarmy
entity: sensor.logwarning
history: 15
collapse: 8
scroll: false
hidden_state:
  - PUSTY
  - niedostępny
  - unavailable
  - unknown
desc: true
state_map:
  - icon: mdi:alert
    value: ERR*
    icon_color: red
  - icon: mdi:information
    value: INF*
    icon_color: purple
show:
  state: true
  duration: false
  start_date: true
  end_date: false
  icon: true
  separator: false
max_items: -1
date_format: DD.MM.YYYY HH:mm:ss
`

EDIT:

Ok. i changed line: 
`  <span class="state">${item.label}</span>`
to:
`<span class="state">${item.label.substring(4)}</span>`
Now, everything work as i want.

**Comment by royto** [comment]
Closing this issue as the card handle multiple entities
