### ISSUE TITLE
Update 1.10.0 let hide everything with hidden_state:   - ''

### ISSUE THREAD

**Issue by SteffenM-DE** [royto/logbook-card#69]
After Update to 1.10.0 all my logbook cards are disappeared. After some testing with remove options I found that the  following option hide everything with version 1.10.0:

```
hidden_state:
  - ''

```
After remove this option the card is back again.

**Comment by royto** [comment]
Can you test by replacing 

```
hidden_state:
  - ''
```

by 

```
hidden_state:
  - state: ''
```

**Comment by SteffenM-DE** [comment]
Sorry with state is also not working and the card is empty.
