### ISSUE TITLE
Card not being handled correctly when removed from DOM

### ISSUE THREAD

**Issue by Sian-Lee-SA** [royto/logbook-card#73]
This card is still calling api history after it has been removed. Seems you're not handling disconnected callbacks and stopping event listeners which is keeping the element alive.

**Comment by royto** [comment]
What do you mean by removed from the DOM ? Changing tabs ? removing the card ? Do you have an example when it occurs ?

there reload of the history is triggered when HA frontend call the shouldUpdate method (there is no api call if HA do not call this method ...

**Comment by Sian-Lee-SA** [comment]
Could be a condition card or dialog... I noticed the action handlers don't have disconnected callbacks.

**Comment by Sian-Lee-SA** [comment]
Network tab on browser shows the calls continue even when navigating away to any page. The only way to stop is refreshing the browser

**Comment by royto** [comment]
I don't reproduce the issue when changing tab or page ...
