### ISSUE TITLE
Custom log entries not showing in card

### ISSUE THREAD

**Issue by itayov** [royto/logbook-card#76]
Custom entries created with logbook.log service are not showing in the card. They are still shown in the logbook menu, and even in the native Logbook Card, but not showing in this custom card.

It might be connected to [this](https://github.com/home-assistant/core/issues/55724) issue that was previously on the native card

**Comment by royto** [comment]
Hello, 

to get entity history, i use the `/api/history/period/<timestamp>` REST API which do not return custom log entries.

Only, the `/api/logbook` REST API returns custom log entries but do not contains all information as history.

This mean that if I implement custom log, I should merge result from both endpoints ... and adapt layout for custom entries ... as there is no state, no attributes, ... Should we compute duration ? based on  what ?

**Comment by itayov** [comment]
@royto What about adding a flag `show_custom_logs`, and if it set to be true, we only show these logs' text and time of being logged?

**Comment by royto** [comment]
Implemented in [1.13.0](https://github.com/royto/logbook-card/releases/tag/1.13.0)
